server:
  port: 8080

spring:
  application:
    name: todo_server

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://localhost:3306/todo_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: freak
    password: password1234!@#$

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true